version: "3.9"
services:
  trade-executor-service:
    container_name: trade-executor-service
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    environment:
      HTTP_PORT: 8080
      ORDER_TIMEOUT_SECONDS: 30
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app/service
